flags: {}
resolver: nightly-2020-07-23
extra-deps:
- git: /home/deech/Haskell/fltkhs
  commit: 652c262c72df0014a9de4c8ae7d234e07505584a

- git: /home/deech/Haskell/fltkhs-fluidtohs
  commit: 5c0d3be266a020c1babe31b4a642ffa1273cff42
